CommitMsg:
  CapitalizedSubject:
    enabled: false
  EmptyMessage:
    enabled: false
  TrailingPeriod:
    enabled: true
  TextWidth:
    enabled: false
PreCommit:
  ALL:
    on_warn: fail
  AuthorEmail:
    enabled: true
  AuthorName:
    enabled: true
  MergeConflicts:
    enabled: true
  YamlSyntax:
    enabled: true
  BundleCheck:
    enabled: true
  RuboCop:
    enabled: true
  Fasterer:
    enabled: true
  BundleAudit:
    enabled: true
  Brakeman:
    enabled: true
  Reek:
    enabled: true
  RailsBestPractices:
    enabled: true
    command: ['rails_best_practices', '--config', 'config/rails_best_practices.yml']
  RailsSchemaUpToDate:
    enabled: true
    description: 'Check if database schema is up to date'
    include:
      - 'db/migrate/*.rb'
      - 'db/schema.rb'
PostCheckout:
  ALL: # Special hook name that customizes all hooks of this type
    quiet: true # Change all post-checkout hooks to only display output on failure
  YarnInstall:
    enabled: true
  BundleInstall:
    enabled: true
