detectors:
  DuplicateMethodCall:
    max_calls: 2
  IrresponsibleModule:
    enabled: false
  NestedIterators:
    max_allowed_nesting: 3
  TooManyStatements:
    enabled: true
    exclude:
      - initialize
    max_statements: 10
  UnusedPrivateMethod:
    enabled: true
directories:
  "app/controllers":
    InstanceVariableAssumption:
      enabled: false
    IrresponsibleModule:
      enabled: false
    NestedIterators:
      max_allowed_nesting: 2
    UncommunicativeModuleName:
      enabled: false
    UnusedPrivateMethod:
      enabled: false
  "app/helpers":
    IrresponsibleModule:
      enabled: false
    UtilityFunction:
      enabled: false
  "app/mailers":
    InstanceVariableAssumption:
      enabled: false
  "app/models":
    InstanceVariableAssumption:
      enabled: false
