inherit_from:
  - https://shopify.github.io/ruby-style-guide/rubocop.yml
Rails:
  Enabled: true
FrozenStringLiteralComment:
  Enabled: false
Layout/DotPosition:
  Enabled: true
  EnforcedStyle: leading
