inherit_from:
  - https://shopify.github.io/ruby-style-guide/rubocop.yml
require: rubocop-rails
Style/FrozenStringLiteralComment:
  Enabled: false
Layout/DotPosition:
  Enabled: true
  EnforcedStyle: leading
