AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'spec/**/*'
    - 'bin/**/*'
    - 'config.ru'
require: rubocop-rails
inherit_from:
  - https://shopify.github.io/ruby-style-guide/rubocop.yml
Style/FrozenStringLiteralComment:
  Enabled: false
Layout/DotPosition:
  Enabled: true
  EnforcedStyle: leading
